lstg.plugin.RegisterEvent("afterTHlib", "Stage Background Extensions", 100, function()
    Include("stage1/stage1.lua")
    Include("stage3/stage3.lua")
    Include("stage4/stage4.lua")
    Include("spellcard/spellcard.lua")
end)